In [3]:
#MD. Saif Niaz
#ID: 100555440

import numpy as np
import matplotlib.pyplot as plt

data = np.random.rand(2,3)

def WhiteWash(c):
    white =  np.ones_like(c)
    temp1 = ((c + white)/2)
    return temp1

print(data)
temp = WhiteWash(data)
print(temp)

#Just to check if colormap works
#plt.imshow(data)
#plt.imshow(temp)

#plt.show()

[[ 0.58579628  0.42571447  0.91559904]
 [ 0.59611495  0.72828745  0.08049743]]
[[ 0.79289814  0.71285723  0.95779952]
 [ 0.79805747  0.86414372  0.54024872]]
