In [22]:
#MD. Saif Niaz
#ID: 100555440

import numpy as np
import matplotlib.pyplot as plt

data = np.random.rand(2,3)

def WhiteWash(c):
    white =  np.ones_like(c)
    temp1 = ((c + white)/2)
    return temp1

print(data)
temp = WhiteWash(data)
print(temp)

#Just to check if colormap works
#plt.imshow(data)
#plt.imshow(temp)

#plt.show()

[[ 0.70885175  0.77637726  0.87817196]
 [ 0.7099792   0.83792703  0.21081394]]
[[ 0.85442587  0.88818863  0.93908598]
 [ 0.8549896   0.91896351  0.60540697]]
